//@author Rohith Ravindranath
//@version July 10 2019
export class PredictHouseInfo {
  constructor(
    public address1:string,
    public address2:string,
    public city:string,
    public state:string,
    public zipcode:string,
    public country:string,
    public lotArea:string,
    public bldgType:string,
    public houseStyle:string,
    public overallCond:string,
    public yearBuilt:string,
    public fullBath:string,
    public halfBath:string,
    public bedroomAbvGr:string,
    public kitchenAbvGr:string,
    public kitchenQual:string,
    public totalRmsAbvGrd:string,
    public heating:string,
    public heatingQC:string,
    public centralAir:string,
    public electrical:string,
    public roofStyle:string,
    public exterCond:string,
    public foundation:string,
    public bsmtCond:string,
    public poolArea:string,
    public poolQC:string,
    public fireplaces:string,
    public fireplaceQu:string,
    public garageType:string,
    public garageFinish:string,
    public garageCars:string,
    public garageCond:string,
    public fence:string,
    public moSold:string,
    public yrSold:string
  ) { }
}
